---
- name: Create nginx module path.
  file:
    path: "{{ nginx_module_path }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    state: directory

- name: Download nginx package.
  get_url:
    url: http://package.sundayle.com/nginx/nginx-{{ nginx_version }}.tar.gz
    dest: "{{ nginx_source_path }}"
    mode: 0644
  register: nginx_package_result

- name: Download nginx module.
  get_url:
    url: "{{ item }}"
    dest: "{{ nginx_module_path }}"
    mode: 0644
  with_items:
    - http://package.sundayle.com/nginx/nginx_module/echo-nginx-module-master.zip
    - http://package.sundayle.com/nginx/nginx_module/headers-more-nginx-module-master.zip
    - http://package.sundayle.com/nginx/nginx_module/nginx_upstream_check_module-master.zip
    - http://package.sundayle.com/nginx/nginx_module/nginx-upload-module-2.2.zip 
    - http://package.sundayle.com/nginx/nginx_module/ngx_cache_purge-2.3.tar.gz 
  register: nginx_module_result
