---
- name: Copy nginx service
  template: 
    src: redhat.service 
    dest: /etc/init.d/nginx 
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0755
  when: ansible_os_family == 'RedHat'

- name: copy nginx service
  template: 
    src: debian.service 
    dest: /etc/init.d/nginx
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}" 
    mode: 0755
  when: ansible_os_family == 'Debian'

- name: Nginx service
  service: 
    name: nginx 
    enabled: yes 
    state: started
