---
- name: Create nginx group
  group: 
    name: "{{ nginx_group }}" 
    state: present

- name: Create nginx user
  user: 
    name: "{{ nginx_user }}" 
    group: "{{ nginx_group }}" 
    shell: /bin/false

