---
- name: Delete unsafe user
  user:
    name: "{{ item }}"
    state: absent
#    remove: yes
    force: yes
  with_items:
    - "{{ del_user }}"

- name: Delete unsafe group
  group:
    name: "{{ del_group }}" 
    state: absent
