---
- name: Disabled NetworkManager.
  service:
    name: NetworkManager
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Disable Firewalld
  systemd: 
    name: firewalld 
    state: stopped
    enabled: no
  ignore_errors: yes
  
