- name: Import key.
  rpm_key:
    state: present
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

- name: Install elrepo rpm.
  yum:
    name: https://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
    state: present

- name: Upgrade kernel to 4.x.
  yum:
    name: kernel-ml
    state: present
    enablerepo: 'elrepo-kernel'

#- name: Print reboot system msg.
#  debug:
#    msg: "Please reboot system."

#- name: "reboot system"
#    command: /sbin/reboot
