---
- name: Run shadowsocks docker.
  docker_container:
    name: ss
    image: sundayle/shadowsocks-libev
    state: started
    restart: yes
    restart_policy: always
    ports:
    - "24781:8388/tcp"
    - "24782:8388/tcp"
    - "24783:8388/tcp"
    - "24784:8388/tcp"
    env:
      METHOD: chacha20-ietf-poly1305
      PASSWORD: sundayle.com
