---
- name: sysctl.conf
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
    sysctl_set: yes
    reload: yes
    ignoreerrors: yes
  with_items: '{{ sysctl_config }}'
