---
nginx_version: 1.14.2
nginx_path: "/usr/local/webserver/nginx"
nginx_conf_path: "{{ nginx_path }}/conf"
nginx_vhosts_path: "{{ nginx_path }}/conf/conf.d"
nginx_log_path: "/data/logs/nginx"
nginx_user: "www"
nginx_group: "www"
nginx_source_path: "/usr/local/src"
nginx_module_path: "/usr/local/src/nginx_module"
configure_args: "
	./configure \
    --prefix={{ nginx_path }} \
    --with-file-aio \
    --with-poll_module \
    --with-http_realip_module \
    --with-http_image_filter_module \
    --with-http_gunzip_module \
    --with-http_gzip_static_module \
    --with-http_addition_module \
    --with-http_sub_module \
    --with-http_dav_module \
    --with-http_flv_module \
    --with-http_mp4_module \
    --with-http_slice_module \
    --with-http_random_index_module \
    --with-http_secure_link_module \
    --with-http_degradation_module \
    --with-http_ssl_module \
    --with-http_v2_module \
    --with-http_stub_status_module \
    --with-http_slice_module \
    --with-http_geoip_module \
    --with-http_auth_request_module \
    --with-stream \
    --with-stream_ssl_module \
    --with-stream_ssl_preread_module \
    --with-stream_realip_module \
    --with-threads \
    --with-pcre \
    --error-log-path={{ nginx_log_path }}/error.log \
    --http-log-path={{ nginx_log_path }}/access.log \
    --add-module=../nginx_module/nginx_upstream_check_module-master \
    --add-module=../nginx_module/echo-nginx-module-master \
    --add-module=../nginx_module/headers-more-nginx-module-master \
    --add-module=../nginx_module/ngx_cache_purge-2.3 \
    --add-module=../nginx_module/nginx-upload-module-2.2"

custom_version: "sunday"
make_args: "make -j {{ ansible_processor_vcpus -2 }} && make install"

