---
#- name: Include OS-specific variables.
#  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'


