---
- name: Delete unsafe user
  user:
    name: "{{ del_user }}"
    state: absent
    remove: yes
    force: yes

- name: Delete unsafe group
  group:
    name: "{{ del_group }}" 
    state: absent

