---
- name: Modify ssh port to {{ ssh_port }}.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    insertafter: "{{ item.insertafter }}"
    line: "{{ item.line }}"
  with_items:
     - { regexp:  '^Port {{ ssh_port }}',insertafter: '^#Port 22',line: 'Port {{ ssh_port }}' }
     - { regexp:  '^PermitRootLogin no',insertafter: '^#PermitRootLogin',line: 'PermitRootLogin no' }
     - { regexp:  '^PubkeyAuthentication yes',insertafter: '^#PubkeyAuthentication',line: 'PubkeyAuthentication yes' }
     - { regexp:  '^PasswordAuthentication no',insertafter: '#PasswordAuthentication',line: 'PasswordAuthentication no' }
     - { regexp:  '^UseDNS no',insertafter: '#UseDNS yes',line: 'UseDNS no' }
     - { regexp:  '^GSSAPIAuthentication no',insertafter: '#GSSAPIAuthentication yes',line: 'GSSAPIAuthentication no' }
  tags:
    - sshd_config 
  notify: restart sshd
