---
- name: start rabbitmq-server
  service: name=rabbitmq-server state=started

- name: restart rabbitmq-server
  service: name=rabbitmq-server state=restarted

- name: reload rabbitmq-server
  service: name=rabbitmq-server state=reloaded
