---
- name: Check if docker-compose is already.
  stat:
    path: /usr/local/bin/docker-compose
  register: docker_compose_result

- name: Download docker-compose.
  get_url:
    url: 'https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64' 
    dest: /usr/local/bin/docker-compose
    mode: 0755
  when: not docker_compose_result.stat.exists

- name: docker-compose version.
  command: docker-compose -version
  register: docker_compose_version_result
  changed_when: false
  ignore_errors: true

- debug: var=docker_compose_version_result.stdout
