---
#- name: Include OS-specific variables.
- include_vars: "{{ ansible_os_family|lower }}.yml"
- include: "{{ ansible_os_family|lower }}/{{ ansible_os_family|lower}}.yml"

- include: common/rc-local.yml
  tags:
    - rc-local

- include: common/ulimit.yml
  tags: 
    - ulimit

- include: common/user_ssh.yml
  tags:
    - user_ssh

- include: common/sshd_config.yml
  tags:
    - sshd_config

#- include: redhat/del_user_group.yml
#  tags:
#    - del_user
#    - del_group
#  when: ansible_os_family == 'RedHat'

- include: redhat/network.yml
  tags:
    - network
  when: ansible_os_family == 'RedHat'

- include: "{{ ansible_os_family|lower }}/docker.yml"
  tags:
    - docker

#- include: common/docker-compose.yml
#  tags:
#    - docker-compose

- include: "{{ ansible_os_family|lower }}/python-pip.yml"
  tags:
    - python
    - python-pip

- include: common/ss.yml
  tags:
    - ss

- include: common/ssr.yml
  tags:
    - ssr

- include: common/sysctl.yml
  tags:
    - sysctl

- include: redhat/upgrade-kernel.yml
  tags:
    - bbr
    - kernel
  when: ansible_os_family == 'RedHat'
