---
#- name: Include OS-specific variables.
- include_vars: "{{ ansible_os_family|lower }}.yml"
- include_tasks: "{{ ansible_os_family|lower }}.yml"
  tags:
    - apt
    - yum

- include_tasks: configure.yml
  tags: 
    - configure

- include_tasks: sysctl.yml
  tags:
    - sysctl

- include_tasks: service.yml
  tags:
    - service

#- include_tasks: redhat.yml
#  when: ansible_os_family == 'RedHat'
#- include_tasks: debian.yml
#  when: ansible_os_family == 'Debian'
